name: Build

on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}

    name: Build on ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install gcc-multilib libzmq3-dev libczmq-dev libjson-c-dev libmsgpack-dev nodejs chromium-browser

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: Install-Module PackageManagement -Force -Repository PSGallery -AllowPrerelease; Install-Module posh-git -Scope CurrentUser -Force; Import-Module posh-git

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ matrix.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ matrix.os }}-gradle-

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew build

      - name: Copying DLLs on Windows
        if: matrix.os == 'windows-latest'
        run: Copy-Item src/nativeMain/resources/mingw/bin/libzmq-mt-4_3_3.dll C:\\Users\\runneradmin\\.konan\\dependencies\\msys2-mingw-w64-x86_64-clang-llvm-lld-compiler_rt-8.0.1\\x86_64-w64-mingw32\\lib

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: ./gradlew build

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip